# Simulation

In [19]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
rng

Generator(PCG64) at 0x12629A4A0

### How likely is it that you roll doubles when rolling two dice?


In [20]:
n_sim = 10**5
n_dice = 2
rolls = rng.choice([1,2,3,4,5,6], n_sim * n_dice).reshape(n_sim,n_dice)
rolls

array([[1, 5],
       [4, 3],
       [3, 6],
       ...,
       [6, 4],
       [3, 1],
       [6, 6]])

In [21]:
pd.DataFrame(rolls).apply(lambda row: row[0] == row[1], axis=1).mean()

0.16704

### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?


In [22]:
n_coins = 8
flips = rng.choice(['heads','tails'], n_sim * n_coins).reshape(n_sim,n_coins)

flip_count = (flips=='heads').sum(axis=1)
flip_count

array([1, 3, 4, ..., 4, 2, 4])

In [23]:
(flip_count == 3).mean()

0.21906

In [24]:
(flip_count > 3).mean()

0.63767

### There are approximately 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?


In [25]:
n_bb = 2
db = rng.choice(['wd','ds'], n_sim * n_bb, p=[0.75,0.25]).reshape(n_sim,n_bb)
db

array([['wd', 'wd'],
       ['ds', 'wd'],
       ['ds', 'wd'],
       ...,
       ['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd']], dtype='<U2')

In [26]:
((db=='ds').sum(axis=1)==2).mean()

0.06349

### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the `np.random.normal`) You'll need to make a judgement call on how to handle some of your values


In [27]:
mu, sigma = 3, 1.5
pop = rng.normal(3, 1.5, size=(10**5,5)).round(0)
pop

array([[2., 3., 7., 4., 4.],
       [4., 4., 4., 1., 4.],
       [3., 3., 2., 2., 5.],
       ...,
       [3., 6., 1., 5., 3.],
       [1., 2., 4., 1., 0.],
       [5., 5., 5., 4., 4.]])

In [28]:
(pop.sum(axis=1)<17).mean()

0.66869

### Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use `np.random.normal` to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [29]:
m_mu, m_sigma = 178, 8
w_mu, w_sigma = 170, 6
mh = rng.normal(m_mu,m_sigma,10**5)
wh = rng.normal(w_mu,w_sigma,10**5)

In [30]:
height = pd.DataFrame([mh,wh]).T
height = height.rename(columns={0:'men',1:'women'})
(height.men<height.women).mean()

0.21054

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?


In [31]:
stu = 50
ana = rng.choice(['good','issue'],n_sim * stu, p=[0.996,0.004]).reshape(n_sim,stu)
((ana=='good').sum(axis=1)==stu).mean()

0.81777

In [32]:
stu = 100
ana = rng.choice(['good','issue'],n_sim * stu, p=[0.996,0.004]).reshape(n_sim,stu)
((ana=='good').sum(axis=1)<stu).mean()

0.32961

In [33]:
stu = 150
ana = rng.choice(['good','issue'],n_sim * stu, p=[0.996,0.004]).reshape(n_sim,stu)
((ana=='good').sum(axis=1)<stu).mean()

0.45163

In [34]:
stu = 450
ana = rng.choice(['good','issue'],n_sim * stu, p=[0.996,0.004]).reshape(n_sim,stu)
((ana=='good').sum(axis=1)==stu).mean()

0.16366

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?


In [35]:
days = 3
food = rng.choice([0,1],n_sim*days,p=[0.3,0.7]).reshape(n_sim,days)
(food.sum(axis=1)==0).mean()

0.02624

In [36]:
days = 7
food = rng.choice([0,1],n_sim*days,p=[0.3,0.7]).reshape(n_sim,days)
((food.sum(axis=1)>=1)).mean()

0.99976

### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [37]:
bdays = range(0,365)
stud = 23
bday = rng.choice(bdays, size=(n_sim,stud))
bday

array([[321, 219, 244, ...,  48, 279, 341],
       [ 28, 106, 315, ..., 207, 217, 142],
       [  4,  15,  88, ..., 229, 208,  52],
       ...,
       [103, 259, 348, ..., 305, 118,   9],
       [227, 358,  45, ...,  35, 223, 308],
       [211, 216, 114, ..., 350, 163, 316]])

In [38]:
bday=pd.DataFrame(bday)
bday

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      321  219  244   87  261   32  295  313  355  123  ...    1   44   97   
1       28  106  315   35   70  314   67  156  330  327  ...    0  327  229   
2        4   15   88   90  307  342  110  180  108   89  ...  348  216  246   
3      359  162  333   91  173   22   85  209  159  160  ...  361  235   55   
4      325  208  109  347   25  180  269  123  357  288  ...  350  251  155   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  160  193   50  322  169  154  203  333  236  106  ...   86  138  134   
99996  314   75  363    7  326   38   33  279  340  246  ...  306  314  122   
99997  103  259  348  275   32  100  129   86  100  146  ...  250   58  336   
99998  227  358   45  268   84   36  311  120  256  132  ...  199  201  157   
99999  211  216  114  107  186  189  210  153  239  358  ...  247   22  265   

        16   17   18   19   20   21   22  
0      279  147  356  345   48  279  341  
1      101  229  142  321  207  217  142  
2      253  139  337  356  229  208   52  
3      320  197  346   76   99  121  204  
4       24   71  167  111  140   75  181  
...    ...  ...  ...  ...  ...  ...  ...  
99995   48  198  116  340   14  218  206  
99996  140  346  338  239   44  332  252  
99997  247  339  171   75  305  118    9  
99998  360  255   54   97   35  223  308  
99999  218  147  116  269  350  163  316  

[100000 rows x 23 columns]

In [39]:
(bday.nunique(axis=1)<stud).mean()

0.50898

In [40]:
stud = 20
bday = pd.DataFrame(rng.choice(bdays, size=(n_sim,stud)))
(bday.nunique(axis=1)<stud).mean()

0.41195

In [41]:
stud = 40
bday = pd.DataFrame(rng.choice(bdays, size=(n_sim,stud)))
(bday.nunique(axis=1)<stud).mean()

0.89145